version: '3.1'
services:
  server:
    build: server
    ports:
      - "9090:9090"
    container_name: server
    image: server_image
    depends_on:
      - StatServerDb
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/StatServerDb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password

  client:
    build: client
    ports:
      - "8080:8080"
    container_name: client
    image: client_image
    environment:
      - STAT_SERVER_URL=http://server:9090

  StatServerDb:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=StatServerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "6541:5432"
