version: '3.1'
services:
  server:
    build: stats-service/server
    ports:
      - "9090:9090"
    container_name: server
    image: server_image
    depends_on:
      - StatServerDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://StatServerDb:5432/StatServerDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  main-service:
      build: main-service
      ports:
        - "8080:8080"
      container_name: main-service
      image: main_image
      depends_on:
        - MainServiceDb
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://MainServiceDb:5432/MainServiceDb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password

  StatServerDb:
    image: postgres:15-alpine
    container_name: StatServerDb
    environment:
      - POSTGRES_DB=StatServerDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "6541:5432"

  MainServiceDb:
      image: postgres:15-alpine
      container_name: MainServiceDb
      environment:
        - POSTGRES_DB=MainServiceDb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      ports:
        - "6541:5432"
